djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('student.urls')),
    path('', include('teacher.urls')),
    path('', include('animal.urls')),
    path('', include('course.urls')),
    path('', include('userextend.urls')),
    path('', include('django.contrib.auth.urls')),
]

home/urls.py
from home import views
from django.urls import path

urlpatterns = [
    path('homepage/', views.homepage, name='home'),
    path('all_students/', views.home, name='list_of_students'),
    path('cars/', views.brands, name='cars'),
    path('', views.HomeTemplateView.as_view(), name='homepage'),
]

student/urls.py
from django.urls import path, include
from rest_framework import routers

from student import views
from student.views import StudentViewSet

router = routers.DefaultRouter()
router.register('api-student', StudentViewSet)

urlpatterns = [
    path('create_student/', views.StudentCreateView.as_view(), name='create-student'),
    path('list_of_students/', views.StudentListView.as_view(), name='list_of_students'),
    path('update_student/<int:pk>/', views.StudentUpdateView.as_view(), name='update_student'),
    path('delete_Student/<int:pk>/', views.StudentDeleteView.as_view(), name='delete_student'),
    path('detailed_student/<int:pk>/', views.StudentDetailView.as_view(), name='detail_student'),
    path('', include(router.urls))
]

student/models.py
from django.db import models
from teacher.models import Teacher


class Student(models.Model):
    gender_choices = (('Male', 'Male'),
                      ('Female', 'Female'),
                      ('Other', 'Other'))

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    age = models.IntegerField()
    date_of_birth = models.DateField()
    olympic = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    gender = models.CharField(max_length=10, choices=gender_choices)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

student/forms.py
from django import forms
from django.forms import TextInput, Select

from animal.models import Animal
from student.models import Student
from teacher.models import Teacher


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'age', 'date_of_birth',
                  'olympic', 'gender', 'teacher']  # campurile pe care le vrem in formular
        widgets = {
            'first_name': TextInput(attrs={'placeholder': 'Please enter your first name', 'class': 'form-control'}),
            'last_name': TextInput(attrs={'placeholder': 'Please enter your last name', 'class': 'form-control'}),
            'age': TextInput(attrs={'placeholder': 'Please enter your age', 'class': 'form-control'}),
            'date_of_birth': TextInput(attrs={'class': 'form-control', 'type': 'date'}),
            'gender': Select(attrs={'placeholder': 'Please your gender', 'class': 'form-control'}),
            'teacher': Select(attrs={'placeholder': 'Please select your specialization', 'class': 'form-control'})
        }

    def __init__(self, *args, **kwargs):
        super(StudentForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].label = 'Prenume'
        self.fields['last_name'].required = False


class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['first_name', 'last_name', 'specialization', 'active']

        widgets = {
            'first_name': TextInput(attrs={'placeholder': 'Please enter your first name', 'class':'form-control'}),
            'last_name': TextInput(attrs={'placeholder': 'Please enter your last name', 'class': 'form-control'}),
            'specialization': Select(attrs={'placeholder': 'Please select your specialization', 'class': 'form-control'}),

        }


class AnimalForm(forms.ModelForm):
    class Meta:
        model = Animal
        fields = ['animal_type', 'animal_name', 'animal_age', 'pure_breed', 'student']

        widgets = {
            'animal_type': TextInput(attrs={'placeholder': 'What type of pet do you have ?', 'class':'form-control'}),
            'animal_name': TextInput(attrs={'placeholder': 'Please enter your pet`s name', 'class':'form-control'}),
            'animal_age': TextInput(attrs={'placeholder': 'Please enter your pet`s age', 'class': 'form-control'}),
            'pure_breed': Select(attrs={'placeholder': 'Is your pet pure breed?', 'class': 'form-control'}),
            'student': Select(attrs={'placeholder': 'Please select the owner of this pet', 'class': 'form-control'})
        }

student/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from rest_framework import viewsets
from student.filters import StudentFilter
from student.forms import StudentForm
from student.models import Student
from student.serializers import StudentSerializer


class StudentCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    template_name = 'student/create_student.html'  #calea catre fisierul html unde va fi afisat forumlarul
    model = Student  # modelul pe care il folosim in generarea formularului nostru
    # fields = '__all__' # returneaza toate field-urile din model
    success_url = reverse_lazy('create-student') #redirectionarea dupa ce formularul a fost validat.
    form_class = StudentForm
    permission_required = 'student.add_student'


class StudentListView(PermissionRequiredMixin, ListView):
    template_name = 'student/list_students.html'
    model = Student
    context_object_name = 'all_students'
    permission_required = 'student.view_student'

    def get_context_data(self, **kwargs):
        data = super(StudentListView, self).get_context_data(**kwargs)
        all_students = Student.objects.all()
        my_filter = StudentFilter(self.request.GET, queryset=all_students)
        all_students = my_filter.qs
        data['all_students'] = all_students
        data['my_filter'] = my_filter
        return data


class StudentUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'student/update_student.html'
    model = Student
    success_url = reverse_lazy('list_of_students')
    form_class = StudentForm
    permission_required = 'student.change_student'


class StudentDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'student/delete_student.html'
    model = Student
    success_url = reverse_lazy('list_of_students')
    form_class = StudentForm
    permission_required = 'student.delete_student'


class StudentDetailView(PermissionRequiredMixin, DetailView):
    template_name = 'student/detail_student.html'
    model = Student
    permission_required = 'student.view_student'


class StudentViewSet(viewsets.ModelViewSet):
    queryset = Student.objects.all()
    serializer_class = StudentSerializer

templates/student/create_student.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Create a new student {% endblock %}

{% block content %}
{% if perms.change_student %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<div class = 'row'>
    <div class="row col-md-6 offset-md-3">
        <form  method="POST">
             {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">Submit</button>
        </form>
    </div>
</div>
    {% endif %}

{% endblock content %}

templates/student/delete_student.html
{% extends 'base.html' %}

{% block title %} {% endblock title %}

{% block content %}
    {% if perms.delete_student %}
    <p>Are you sure you want to delete {{ student.first_name }} {{ student.last_name }} ?</p>

    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Yes</button>
        <a href="{% url 'list_of_students' %}" class="btn btn-default">No</a>

    </form>
    {% endif %}
{% endblock content %}

templates/student/detail_student.html
{% extends 'base.html' %}

{% block title %}Detailed View Student {% endblock title %}

{% block content %}
    {% if perms.view_student %}
    <div class="card text-center">
        <div class="card-header">


            Created at: {{ student.created_at }}
        </div>
        <div class="card-body">
            <h5 class="card-title">  {{ student.first_name }} {{ student.last_name }}</h5>
            <p>Age: {{ student.age }}</p>
            <p> Gender: {{ student.gender }}</p>
            <p> Teacher: {{ student.teacher.first_name }} {{ student.teacher.last_name }}</p>
            <p>Date of birth: {{ student.date_of_birth }}</p>
            <p>Olympic: {{ student.olympic }}</p>
            <a href="{% url 'list_of_students' %}" class="btn btn-primary">Go to list of student</a>
        </div>
        <div class="card-footer text-muted">

            Registry updated at: {{ student.updated_at }}
        </div>
    </div>
{% endif %}

{% endblock %}

templates/student/get_all_students_per_teacher.html
{% extends 'base.html' %}
{% block title %} All Students {% endblock title %}



{% block content %}
    <div style="margin-top:200px">
    <table class="table">
        <thead>
            <tr>
                <th>Full Name</th>
                <th>Age</th>
            </tr>
        </thead>
        <tbody>
        {% for student in students %}
            <tr>
            <td>{{ student.first_name }} {{ student.last_name }}</td>
            <td>{{ student.age }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>

{% endblock content %}

templates/student/list_students.html
{% extends 'base.html' %}
{% block title %}List of Students{% endblock title %}
{% load static %}

{% block content %}
    {% if perms.view_student %}
    <link rel="stylesheet" href="{% static 'css/student_list.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css"
          integrity="sha256-2XFplPlrFClt0bIdPgpz8H7ojnk10H69xRqd9+uTShA=" crossorigin="anonymous"/>

    <div style="margin-bottom: 20px">
        <div class='col'>
            <div class="col-md-3 offset-md-4">
                <form method="GET">
                    {{ my_filter.form }}
                    <div class='offset-md-5' style="margin-top: 10px;">
                        <button type="submit" class="btn btn-success">Search</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="container mt-3 mb-4">
        <div class="col-lg-9 mt-4 mt-lg-0">
            <div class="row">
            {% if perms.student.view_student %}
                <div class="col-md-12">
                    <div class="align-content-center" style="margin-bottom:10px">
                        <a href="{% url 'create-student' %}" class="btn btn-success">Add a new Student</a>
                    </div>
                {% endif %}
                    <div class="user-dashboard-info-box table-responsive mb-0 bg-transparent p-4 shadow-sm">

                        <table class="table manage-candidates-top mb-0">
                            <thead>
                            <tr>
                                <th>Student Name</th>
                                <th class="text-center">Age</th>
                                <th class="text-center">Assigned Proffesor</th>
                                <th class="action text-right">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for student in all_students %}
                                <tr class="candidates-list">
                                    <td class="title">
                                        <div class="thumb">
                                            <img class="img-fluid"
                                                 src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="">
                                        </div>
                                        <div class="candidate-list-details">
                                            <div class="candidate-list-info">
                                                <div class="candidate-list-title">
                                                    <h5 class="mb-0 text-light"><a
                                                            href="#">{{ student.first_name }} {{ student.last_name }}</a>
                                                    </h5>
                                                </div>
                                                <div class="candidate-list-option">
                                                    <ul class="list-unstyled">
                                                        <li><i class="fas fa-filter pr-1"></i>Age: {{ student.age }}
                                                        </li>
                                                        <li><i class="fas fa-map-marker-alt pr-1"></i>Assigned
                                                            Proffesor: {{ student.teacher.first_name }} {{ student.teacher.last_name }}
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="candidate-list-favourite-time text-center">
                                        <a class="candidate-list-favourite order-2 text-danger" href="#"><i
                                                class="fas fa-heart"></i></a>
                                        <span class="candidate-list-time order-1">{{ student.age }}</span>
                                    </td>
                                    <td class="candidate-list-favourite-time text-center">
                                        <a class="candidate-list-favourite order-2 text-danger" href="#"><i
                                                class="fas fa-address-card"></i></a>
                                        <span class="candidate-list-time order-1">{{ student.teacher.first_name }} {{ student.teacher.last_name }}</span>
                                    </td>
                                    <td>
                                        <ul class="list-unstyled mb-0 d-flex justify-content-end">
                                            <li><a href="{% url 'detail_student' student.id %}" class="text-primary"
                                                   data-toggle="tooltip" title="" data-original-title="view"><i
                                                    class="far fa-eye"></i></a></li>
                                            <li><a href="{% url 'update_student' student.id %}" class="text-info"
                                                   data-toggle="tooltip" title="" data-original-title="Edit"><i
                                                    class="fas fa-pencil-alt"></i></a></li>
                                            <li><a href="{% url 'delete_student' student.id %}" class="text-danger"
                                                   data-toggle="tooltip" title="" data-original-title="Delete"><i
                                                    class="far fa-trash-alt"></i></a></li>
                                        </ul>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <div class="text-center mt-3 mt-sm-3">
                            <ul class="pagination justify-content-center mb-0">
                                <li class="page-item disabled"><span class="page-link">Prev</span></li>
                                <li class="page-item active" aria-current="page"><span class="page-link">1 </span> <span
                                        class="sr-only">(current)</span></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item"><a class="page-link" href="#">...</a></li>
                                <li class="page-item"><a class="page-link" href="#">25</a></li>
                                <li class="page-item"><a class="page-link" href="#">Next</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endif %}
{% endblock content %}

templates/student/update_student.html
{% extends 'base.html' %}
{% block title %}Update Student{% endblock title %}
{% block content %}
    {% if perms.change_student %}
    <div class = 'row'>
    <div class="row col-md-6 offset-md-3">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary"> Submit Update</button>
    </form>
    </div>
    </div>
    {% endif %}
{% endblock content %}