djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('student.urls')),
    path('', include('teacher.urls')),
    path('', include('animal.urls')),
    path('', include('course.urls')),
    path('', include('userextend.urls')),
    path('', include('django.contrib.auth.urls')),
]

home/urls.py
from home import views
from django.urls import path

urlpatterns = [
    path('homepage/', views.homepage, name='home'),
    path('all_students/', views.home, name='list_of_students'),
    path('cars/', views.brands, name='cars'),
    path('', views.HomeTemplateView.as_view(), name='homepage'),
]

teacher/urls.py
from django.urls import path, include
from rest_framework import routers

from teacher import views
from teacher.views import TeacherViewSet

router = routers.DefaultRouter()
router.register('api-teacher', TeacherViewSet)

urlpatterns = [
    path('teacher/', views.TeacherCreateView.as_view(), name='teacher'),
    path('teacher_list/', views.TeacherListView.as_view(), name='all_teachers'),
    path('teacher_update/<int:pk>/', views.TeacherUpdateView.as_view(), name='teacher_update'),
    path('teacher_delete/<int:pk>/', views.TeacherDeleteView.as_view(), name='delete_teacher'),
    path('teacher_details/<int:pk>/', views.TeacherDetailsView.as_view(), name='teacher_details'),
    path('student_per_teacher/<int:id_teacher>/', views.get_all_students_per_teacher, name='students_per_teacher'),
    path('', include(router.urls))
]

teacher/models.py
from django.db import models


class Teacher(models.Model):
    specialization = (('Geography', 'Geography'),
                      ('Math', 'Math'),
                      ('History', 'History'),)

    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    specialization = models.CharField(max_length=40, choices=specialization)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.first_name} - {self.last_name}"

teacher/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from rest_framework import viewsets

from student.forms import TeacherForm
from student.models import Student
from teacher.filters import TeacherFilter
from teacher.models import Teacher
from teacher.serializers import TeacherSerializer


class TeacherCreateView(CreateView):
    template_name = 'teacher/teacher.html'
    model = Teacher
    success_url = reverse_lazy('teacher')
    form_class = TeacherForm


class TeacherListView(PermissionRequiredMixin, ListView):
    template_name = 'teacher/teacher_list.html'
    model = Teacher
    context_object_name = 'teacher_list'
    permission_required = 'teacher.view_teacher'

    def get_context_data(self, **kwargs):
        data = super(TeacherListView, self).get_context_data(**kwargs)
        all_teachers = Teacher.objects.all()
        my_filter = TeacherFilter(self.request.GET, queryset=all_teachers)
        all_teachers = my_filter.qs
        data['teacher_list'] = all_teachers
        data['my_filter'] = my_filter
        return data


class TeacherUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'teacher/teacher_update.html'
    model = Teacher
    success_url = reverse_lazy('all_teachers')
    form_class = TeacherForm
    permission_required = 'teacher.change_teacher'


class TeacherDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'teacher/delete_teacher.html'
    model = Teacher
    success_url = reverse_lazy('all_teachers')
    permission_required = 'teacher.delete_teacher'


class TeacherDetailsView(PermissionRequiredMixin, DetailView):
    template_name = 'teacher/details_teacher.html'
    model = Teacher
    permission_required = 'teacher.view_teacher'


def get_all_students_per_teacher(request, id_teacher):

    all_students_per_teacher = Student.objects.filter(teacher_id=id_teacher)
    context = {'students': all_students_per_teacher}

    return render(request, 'student/get_all_students_per_teacher.html', context)


class TeacherViewSet(viewsets.ModelViewSet):
    queryset = Teacher.objects.all()
    serializer_class = TeacherSerializer

templates/teacher/delete_teacher.html
{% extends 'base.html' %}

{% block title %} {% endblock title %}

{% block content %}
    {% if perms.delete_teacher %}
    <p>Are you sure you want to delete {{ teacher.first_name }} {{ teacher.last_name }} ?</p>

    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Yes</button>
        <a href="{% url 'all_teachers' %}" class="btn btn-default">No</a>
    </form>
    {% endif %}
{% endblock content %}

templates/teacher/details_teacher.html
{% extends 'base.html' %}

{% block title %}Detailed View Teacher {% endblock title %}


{% block content %}
{% if perms.view_teacher %}
    <div class="card text-center">
        <div class="card-header">
            Created at: {{ teacher.created_at }}
        </div>
        <div class="card-body">
            <h5 class="card-title">  {{ teacher.first_name }} {{ teacher.last_name }}</h5>
            <p>Specialization: {{ teacher.specialization }}</p>
            <p> Teacher: {{ teacher.first_name }} {{ teacher.last_name }}</p>
            {% if teacher.active == True %}
                <p>The teacher is active</p>
            {% else %}
                <p>The teacher is in heaven now</p>
            {% endif %}
            <a href="{% url 'all_teachers' %}" class="btn btn-primary">Go to list of Teachers</a>
        </div>
        <div class="card-footer text-muted">
            Registry updated at: {{ teacher.updated_at }}
        </div>
    </div>
{% endif %}
{% endblock %}

templates/teacher/teacher.html
{% extends 'base.html' %}
{% block title %} Teacher {% endblock title %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<div class = 'row'>
    <div class="row col-md-6 offset-md-3">
        <form  method="POST">
             {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">Submit</button>
        </form>
    </div>
</div>

{% endblock content %}

templates/teacher/teacher_list.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load static %}


{% block content %}
    {% if perms.view_teacher %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">

    <div style="margin-bottom: 20px">
        <div class='col'>
            <div class="col-md-3 offset-md-4">
                <form method="GET">
                    {{ my_filter.form }}
                    <div class='offset-md-5' style="margin-top: 10px;">
                        <button type="submit" class="btn btn-success">Search</button>
                    </div>
                </form>
            </div>
        </div>
        {% if perms.teacher.add_teacher %}
        <div style=" margin-top: 20px">
            <a href="{% url 'teacher' %}" class="btn btn-dark">Add a new teacher</a>
        </div>
        {% endif %}
    </div>

    <div style="display: flex; flex-direction: row; flex-wrap: wrap">
        {% for teacher in teacher_list %}
            <div class="card bg-dark text-light" style="margin-right: 10px">
                <div class="card-body">
                    <div style="display: flex; flex-direction: row">
                        <h5 class="card-title">{{ teacher.first_name }} {{ teacher.last_name }}</h5>
                    </div>
                    <p class="card-text ">{{ teacher.specialization }} </p>
                    {% if teacher.active == True %}
                        <p class="card-text ">The teacher is active </p>
                    {% else %}
                        <p class="card-text ">The teacher is in heaven now. </p>
                    {% endif %}
                    <p class="card-text ">Teacher description to be entered here </p>
                    <a href="{% url 'teacher_update' teacher.id %}" class="btn btn-primary">Update</a>
                    <a href="{% url 'delete_teacher' teacher.id %}" class="btn btn-danger">Delete</a>
                    <a href="{% url 'teacher_details' teacher.id %}" class="btn btn-info">More Details</a>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    </div>

{% endblock content %}

templates/teacher/teacher_update.html
{% extends 'base.html' %}
{% block title %}Update Teacher{% endblock title %}
{% load static %}

{% block content %}
    {% if perms.change_teacher %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <div class = 'row'>
    <div class="row col-md-6 offset-md-3">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit Update</button>
    </form>
    </div>
    </div>
    {% endif %}
{% endblock content %}