djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('student.urls')),
    path('', include('teacher.urls')),
    path('', include('animal.urls')),
    path('', include('course.urls')),
    path('', include('userextend.urls')),
    path('', include('django.contrib.auth.urls')),
]

home/urls.py
from home import views
from django.urls import path

urlpatterns = [
    path('homepage/', views.homepage, name='home'),
    path('all_students/', views.home, name='list_of_students'),
    path('cars/', views.brands, name='cars'),
    path('', views.HomeTemplateView.as_view(), name='homepage'),
]

student/models.py
from django.db import models
from teacher.models import Teacher


class Student(models.Model):
    gender_choices = (('Male', 'Male'),
                      ('Female', 'Female'),
                      ('Other', 'Other'))

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    age = models.IntegerField()
    date_of_birth = models.DateField()
    olympic = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    gender = models.CharField(max_length=10, choices=gender_choices)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

teacher/models.py
from django.db import models


class Teacher(models.Model):
    specialization = (('Geography', 'Geography'),
                      ('Math', 'Math'),
                      ('History', 'History'),)

    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    specialization = models.CharField(max_length=40, choices=specialization)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.first_name} - {self.last_name}"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static '/css/styles.css' %}" rel="stylesheet"/>

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300i,400" rel="stylesheet">
    {% block title %} <title>UBB Cluj-Napoca</title> {% endblock title %}
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet"
          type="text/css"/>
    <!-- Core theme CSS (includes Bootstrap)-->

</head>
<body id="page-top">
<!-- Navigation-->
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{% url 'homepage' %}">UBB Cluj-Napoca</a>
        <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button"
                data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive"
                aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">
                {% if perms.teacher.view_teacher %}
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded"
                                                         href="{% url 'all_teachers' %}">Teachers</a></li>
                {% endif %}
                {% if perms.student.view_student %}
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded"
                                                         href="{% url 'list_of_students' %}">Students</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded"
                                                         href="{% url 'homepage' %}">About</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded"
                                                         href="{% url 'logout' %}">Logout</a></li>


{#                    <div class="collapse navbar-collapse" id="navbarResponsive" >#}
{#                        <div class="dropdown-item"> List of teachers#}
{#                        {% for teacher in teachers %}#}
{#                            <li class="nav-item mx-0 mx-lg-1">#}
{#                        <a href="{% url 'students_per_teacher' teacher.id %}">{{ teacher.first_name }} {{ teacher.last_name }}</a>#}
{#                        {% endfor %}#}
{#                             </li>#}
{#                        </div>#}
{#                    </div>#}
{##}
{#                    <div class="collapse navbar-collapse" id="navbarResponsive" >#}
{#                        <div class="dropdown-item"> List of teachers#}
{#                        {% for teacher in teachers %}#}
{#                            <li class="nav-item mx-0 mx-lg-1">#}
{#                        <a href="{% url 'course_per_teacher' teacher.id %}">{{ teacher.first_name }} {{ teacher.last_name }}</a>#}
{#                        {% endfor %}#}
{#                             </li>#}
{#                        </div>#}
{#                    </div>#}
{##}
{#                      <div class="collapse navbar-collapse" id="navbarResponsive" >#}
{#                        <div class="dropdown-item"> List of courses#}
{#                        {% for course in courses %}#}
{#                            <li class="nav-item mx-0 mx-lg-1">#}
{#                        <a href="{% url 'teacher_per_course' course.teacher.id %}">{{ course.name }}</a>#}
{#                        {% endfor %}#}
{#                             </li>#}
{#                        </div>#}
{#                    </div>#}
{#s#}

                {% else %}
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded"
                                                         href="#about">About</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded"
                                                         href="{% url 'login' %}">Login</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded"
                                                         href="{% url 'create_user' %}">Sign Up</a></li>

                    <
                {% endif %}
            </ul>
        </div>
    </div>

</nav>
<div class='bg-secondary' style="margin-bottom: 110px; solid-color: #1abc9c;"></div>
{% block content %} {% endblock %}
</body>
</html>